// Generated by CoffeeScript 1.7.1
(function() {
  var Parse, PeggParse, Promise, fs, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  Promise = require('bluebird');

  Parse = Promise.promisifyAll(require('node-parse-api').Parse);

  _ = require('underscore');

  PeggParse = (function() {
    function PeggParse(appId, masterKey) {
      this.clearHasPegged = __bind(this.clearHasPegged, this);
      this.clearHasPreffed = __bind(this.clearHasPreffed, this);
      this.deletePeggs = __bind(this.deletePeggs, this);
      this.deletePrefs = __bind(this.deletePrefs, this);
      this._parse = new Parse(appId, masterKey);
    }

    PeggParse.prototype.resetUser = function(userId, cb) {
      var clearedHasPegged, clearedHasPreffed, deletedPeggs, deletedPrefs, user;
      user = {
        __type: "Pointer",
        className: "_User",
        objectId: userId
      };
      deletedPrefs = this.deletePrefs(user);
      deletedPeggs = this.deletePeggs(user);
      clearedHasPreffed = this.clearHasPreffed(userId);
      clearedHasPegged = this.clearHasPegged(userId);
      return Promise.all([deletedPrefs, deletedPeggs, clearedHasPreffed, clearedHasPegged]);
    };

    PeggParse.prototype.deletePrefs = function(user) {
      return this._parse.findAsync('Pref', {
        user: user
      }).then((function(_this) {
        return function(data) {
          var i, pref, prefRowsDeleted, _i, _len, _ref;
          prefRowsDeleted = [];
          _ref = data.results;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            pref = _ref[i];
            prefRowsDeleted[i] = _this._parse.deleteAsync('Pref', pref.objectId).then(function(pref) {
              var message;
              message = "deleted pref: " + (JSON.stringify(pref));
              console.log(message);
              return {
                message: message,
                pref: pref
              };
            });
          }
          return Promise.all(prefRowsDeleted);
        };
      })(this));
    };

    PeggParse.prototype.deletePeggs = function(user) {
      return this._parse.findAsync('Pegg', {
        user: user
      }).then((function(_this) {
        return function(data) {
          var i, pegg, peggRowsDeleted, _i, _len, _ref;
          peggRowsDeleted = [];
          _ref = data.results;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            pegg = _ref[i];
            peggRowsDeleted[i] = _this._parse.deleteAsync('Pegg', pegg.objectId).then(function(pegg) {
              var message;
              message = "deleted pegg: " + (JSON.stringify(pegg));
              console.log(message);
              return {
                message: message,
                pegg: pegg
              };
            });
          }
          return Promise.all(peggRowsDeleted);
        };
      })(this));
    };

    PeggParse.prototype.clearHasPreffed = function(userId) {
      return this.getTable('Card').then((function(_this) {
        return function(results) {
          var card, i, preffedRowsCleared, _i, _len;
          preffedRowsCleared = [];
          for (i = _i = 0, _len = results.length; _i < _len; i = ++_i) {
            card = results[i];
            if ((card.hasPreffed != null) && card.hasPreffed.indexOf(userId) > -1) {
              card.hasPreffed = _.uniq(card.hasPreffed).splice(userId, 1);
              preffedRowsCleared[i] = _this._parse.updateAsync('Card', card.objectId, card).then(function(card) {
                var message;
                message = "cleared hasPreffed from card: " + card.objectId;
                console.log(message);
                return {
                  message: message,
                  card: card
                };
              });
            }
          }
          return Promise.all(preffedRowsCleared);
        };
      })(this));
    };

    PeggParse.prototype.clearHasPegged = function(userId) {
      return this.getTable('Pref').then((function(_this) {
        return function(results) {
          var card, i, peggedRowsCleared, _i, _len;
          peggedRowsCleared = [];
          for (i = _i = 0, _len = results.length; _i < _len; i = ++_i) {
            card = results[i];
            if ((card.hasPegged != null) && card.hasPegged.indexOf(userId) > -1) {
              card.hasPegged = _.uniq(card.hasPegged).splice(userId, 1);
              peggedRowsCleared[i] = _this._parse.updateAsync('Pref', card.objectId, card).then(function(card) {
                var message;
                message = "cleared hasPegged from card: " + card.objectId;
                console.log(message);
                return {
                  message: message,
                  card: card
                };
              });
            }
          }
          return Promise.all(peggedRowsCleared);
        };
      })(this));
    };

    PeggParse.prototype.getTable = function(type, cb) {
      return this.getRows(type, 50, 0, [], function(items) {
        return cb(items);
      });
    };

    PeggParse.prototype.getRows = function(type, limit, skip, res, cb) {
      return this._parse.findManyAsync(type, "?limit=" + limit + "&skip=" + skip, (function(_this) {
        return function(err, data) {
          var item, _i, _len, _ref;
          if ((data != null) && (data.results != null) && data.results.length > 0) {
            _ref = data.results;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              res.push(item);
            }
            return _this.getRows(type, limit, skip + limit, res, cb);
          } else {
            return cb(res);
          }
        };
      })(this));
    };

    PeggParse.prototype.updateRow = function(type, id, json, cb) {
      return this._parse.updateAsync(type, id, json, function(err, data) {
        if (err != null) {
          return cb(err);
        } else {
          return cb(data);
        }
      });
    };

    return PeggParse;

  })();

  module.exports = PeggParse;

}).call(this);
