// Generated by CoffeeScript 1.8.0
(function() {
  var Admin, io;

  io = window.io.connect();

  io.on('update', function(message) {
    return $('#resetUser_detail').append("" + message + "<br/>");
  });

  io.on('done', function(userId, results) {
    $('#resetUser_message').html("Success! User " + userId + " is fresh like spring pheasant").parent().addClass('has-success');
    return $('#resetUser_detail').append("done!");
  });

  io.on('error', function(error) {
    $('#resetUser_message').html(error.message).parent().addClass('has-error');
    return $('#resetUser_detail').html(JSON.stringify(error));
  });

  io.on('message', function(message) {
    return console.log("server says: ", message);
  });

  Admin = {
    resetUser: function(userId) {
      $('#resetUser_message').html("working ...").parent().removeClass('has-success').removeClass('has-error');
      $('#resetUser_detail').html("");
      return io.emit("resetUser", userId);
    }
  };

  window.Admin = Admin;

  $(document).ready(function() {
    $('#resetUser').on('submit', function() {
      Admin.resetUser($('#resetUser_id').val());
      return false;
    });
    return io.emit('ready');
  });

}).call(this);
